---
apiVersion: v1
kind: Service
metadata: { name: database-server, namespace: freva }
spec:
  type: ClusterIP
  selector: { app: database-server }
  ports: [{ port: 3306, targetPort: 3306, name: mysql }]
---
apiVersion: apps/v1
kind: StatefulSet
metadata: { name: database-server, namespace: freva }
spec:
  serviceName: database-server
  replicas: 1
  selector: { matchLabels: { app: database-server } }
  template:
    metadata: { labels: { app: database-server } }
    spec:
      securityContext: { fsGroup: 0 }
      containers:
        - name: mysql
          image: ghcr.io/freva-org/freva-mysql:9.3.0
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 3306, name: mysql }]
          env:
            - name: ROOT_PW
              valueFrom: { secretKeyRef: { name: freva-secrets, key: MYSQL_ROOT_PASSWORD } }
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: freva-secrets, key: MYSQL_ROOT_PASSWORD } }
            - { name: MYSQL_USER, value: "freva" }
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: freva-secrets, key: MYSQL_PASSWORD } }
            - { name: MYSQL_DATABASE, value: "frevadb" }
            - { name: HOST, value: "localhost" }
            - { name: PROJECT, value: "freva" }
          volumeMounts:
            - { name: db-data, mountPath: /data/db }
            - { name: db-logs, mountPath: /data/logs }
          readinessProbe: { tcpSocket: { port: 3306 }, initialDelaySeconds: 5, periodSeconds: 5 }
          livenessProbe:  { tcpSocket: { port: 3306 }, initialDelaySeconds: 10, periodSeconds: 10 }
      volumes:
        - name: db-data
          persistentVolumeClaim: { claimName: db-data }
        - name: db-logs
          persistentVolumeClaim: { claimName: db-logs }
