---
apiVersion: v1
kind: Service
metadata:
  name: web-reverse-proxy
  namespace: freva
  labels:
    app: web-app
    app.kubernetes.io/name: freva
    app.kubernetes.io/instance: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/part-of: freva
    app.kubernetes.io/version: 2510.3.3
    app.kubernetes.io/managed-by: ansible
    freva.org/stateful: "false"
    freva.org/tier: frontend
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-utils
  namespace: freva
  labels:
    app: web-app
    app.kubernetes.io/name: freva
    app.kubernetes.io/instance: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/part-of: freva
    app.kubernetes.io/version: 2510.3.3
    app.kubernetes.io/managed-by: ansible
    freva.org/stateful: "false"
    freva.org/tier: frontend
data:
  wait-for.sh: |
    #!/bin/sh
    set -e
    for host in database-server:3306 cache-server:6379 freva-rest-server:7777; do
      for i in $(seq 1 60); do
        nc -z "$(echo "$host" | cut -d: -f1)" "$(echo "$host" | cut -d: -f2)" && break
        sleep 1
      done
    done
    exit 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: freva
  labels:
    app: web-app
    app.kubernetes.io/name: freva
    app.kubernetes.io/instance: web-app
    app.kubernetes.io/component: web-app
    app.kubernetes.io/part-of: freva
    app.kubernetes.io/version: 2510.3.3
    app.kubernetes.io/managed-by: ansible
    freva.org/stateful: "false"
    freva.org/tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        app.kubernetes.io/name: freva
        app.kubernetes.io/instance: web-app
        app.kubernetes.io/component: web-app
        app.kubernetes.io/part-of: freva
        app.kubernetes.io/version: 2510.3.3
        app.kubernetes.io/managed-by: ansible
        freva.org/stateful: "false"
        freva.org/tier: frontend
    spec:
      securityContext:
        fsGroup: 0
      initContainers:
        - name: wait-prereqs
          image: busybox:stable
          command: ["sh", "-c", "/bin/wait-for.sh"]
          volumeMounts:
            - name: wait-script
              mountPath: /bin/wait-for.sh
              subPath: wait-for.sh
          resources:
            limits:
              cpu: "50m"
              cpu: "50m"
              memory: "256Mi"
      containers:
        - name: nginx
          image: ghcr.io/freva-org/freva-nginx:1.29.3
          imagePullPolicy: IfNotPresent
          resources: {'limits': {'cpu': '1600m', 'memory': '2Gi'}, 'requests': {'cpu': '600m', 'memory': '1Gi'}}
          env:
            - {name: SERVER_ROOT, value: "/srv/static"}
            - {name: VAULT_HOST, value: "vault-server:5002"}
            - {name: FREVA_REST_HOST, value: "freva-rest-server:7777"}
            - {name: EVALUATION_SYSTEM_CONFIG_FILE, value: "/gpfs/csfs1/work/gdexdata/freva/freva/evaluation_system.conf"}
            - {name: CHATBOT_HOST, value: "localhost"}
            - {name: WEB_SERVER_NAME, value: "127.0.0.1"}
            - {name: WEB_SERVER_PORT, value: "8000"}
            - {name: REST_PROXY_HOST_NAME, value: "http://ferva-api.k8s.ucar.edu"}
            - {name: FILL_COLOR, value: "#121212"}
            - {name: PROXY_USER, value: "nobody"}
            - {name: PROJECT_NAME, value: "freva"}
            - {name: PORT_HTTPSD, value: "8443"}
            - {name: PORT_HTTPD, value: "8080"}
            - {name: NO_HTTP_CERT, value: "1" }
            - {name: WEB_HOST, value: "freva.k8s.ucar.edu"}
          volumeMounts:
            - {name: web-static, mountPath: /srv/static}
            - {name: logs, mountPath: /tmp/nginx }
            - {name: core-preview, mountPath: /srv/static/preview, readOnly: true}

        - name: web-app
          image: ghcr.io/freva-org/freva-web:2510.3.3
          imagePullPolicy: IfNotPresent
          resources: {'limits': {'cpu': '1600m', 'memory': '2Gi'}, 'requests': {'cpu': '600m', 'memory': '1Gi'}}
          env:
            - name: EVALUATION_SYSTEM_CONFIG_FILE
              value: "/gpfs/csfs1/work/gdexdata/freva/freva/evaluation_system.conf"
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freva-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: ALLOWED_HOSTS
              value: "freva-httpd,freva.k8s.ucar.edu,localhost,www.freva.k8s.ucar.edu"
            - name: FREVA_WEB_CONFIG_FILE
              value: "/gpfs/csfs1/work/gdexdata/freva/freva/web/freva_web_conf.toml"
            - name: SCHEDULER_HOST
              value: "caspar.hpc.ucar.edu"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://freva.k8s.ucar.edu,https://localhost,https://www.freva.k8s.ucar.edu,https://www.localhost"
            - name: FREVA_BIN
              value: "/gpfs/csfs1/work/gdexdata/conda-env/bin"
            - name: COLUMNS
              value: "140"
            - name: REDIS_HOST
              value: "cache-server"
            - name: FREVA_REST_URL
              value: "http://freva-rest-server:7777"
            - name: REDIS_PASSWD
              valueFrom:
                secretKeyRef:
                  name: freva-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: freva-secrets
                  key: REDIS_USERNAME
            - name: OIDC_DISCOVERY_URL
              value: "https://freva-keycloak.cloud.dkrz.de/realms/Freva/.well-known/openid-configuration"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: freva-secrets
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_CLIENT_ID
              value: "freva"
            - name: CHATBOT_HOST
              value: "localhost"
            - name: STAC_BROWSER
              value: "1"
            - name: DB_USER
              value: "freva"
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: freva-secrets
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              value: "frevadb"
            - name: DB_HOST
              value: "database-server"
            - name: VAULT_URL
              value: "http://vault-server:5002"
            - name: PATH
              value: "/opt/conda/envs/freva-web/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          volumeMounts:
            - name: web-ext
              mountPath: "/gpfs/csfs1/work/gdexdata/"
              readOnly: true
            - name: web-static
              mountPath: /opt/freva_web/static
      volumes:
        - name: web-static
          persistentVolumeClaim:
            claimName: web-data
        - name: logs
          persistentVolumeClaim:
            claimName: proxy-logs
        - name: wait-script
          configMap:
            name: wait-utils
            defaultMode: 0755
        - name: web-ext
          nfs:
            path: /gpfs/csfs1/work/gdexdata/
            readOnly: true
            server: gladedm1.ucar.edu
        - name: core-preview
          nfs:
            path: /gpfs/csfs1/work/gdexdata/freva/share/preview
            readOnly: true
            server: gladedm1.ucar.edu
